### ISSUE TITLE
Housekeeping

### ISSUE THREAD

**Issue by TigBuh99** [b-yp/logseq-insert-movie-properties#12]
Just wondering is there a way to delete unique properties related to a movie if I delete the movie? I mean that if I delete the movie "The Raiders of the Lost Ark", it would be reasonable to delete all pages (properties) that were created when I entered the movie in the first place. Provided that they are not used elsewhere in the graph. I don't know if Logseq has an in-built way to do this, an advanced query maybe?

**Comment by b-yp** [comment]
If you want to delete a movie, you may need to navigate to the movie page and click on "delete page" to remove the page itself. After that, you can delete the corresponding movie entry. These actions are part of Logseq's functionality and are not within the scope of the plugin.
