### ISSUE TITLE
TV series - how to add based on the tt code?

### ISSUE THREAD

**Issue by TigBuh99** [b-yp/logseq-insert-movie-properties#14]
I tried adding a TV series based on its title, as per usual, but I wasn't successful. Specifically, I wanted to add Masterchef, the UK version. I chose this one because there are many similarly named series worldwide and I think that it was a good test. This one has the IMDB code tt0805418 and the title on the IMDB website is "Masterchef Goes Large". The plugin doesn't find it.

Can we add a TV series based on the tt code as input?

**Comment by b-yp** [comment]
The plugin uses the TMDB API, but I couldn't find this TV show on the official TMDB website.

TMDB: https://www.themoviedb.org/

**Comment by TigBuh99** [comment]
It's this one: https://www.themoviedb.org/tv/25992-masterchef-goes-large
:)  

Probably the 25992 is a unique code?

**Comment by b-yp** [comment]
This is currently a flaw in the plugin. The same name may correspond to multiple TV shows or movies, but the plugin defaults to the first result. As a result, some TV shows or movies may never be found (because they may not be ranked first). The next step for the plugin is to return search results in the form of a list for users to choose from, so that they can select the correct one.

**Comment by TigBuh99** [comment]
I agree. I saw something similar to what you say in Obsidian where the input returns a list of Films or TV series and the user picks what he/she wants.

**Comment by b-yp** [comment]
Yes, this task may be completed within this week.

**Comment by TigBuh99** [comment]
Thank you for your paying attention to it. This plugin is going to become one of my favorite plugins in Logseq!!

**Comment by b-yp** [comment]
Thank you very much for your affirmation. It is also one of my motivations for writing this plugin ❤.

**Comment by b-yp** [comment]
I just released a version, added the functionality of list selection.
![image](https://github.com/b-yp/logseq-insert-movie-properties/assets/32813227/e4f4cd6f-b6c5-45ef-8a39-8a430c8f98ad)

**Comment by TigBuh99** [comment]
I haven't tested much, but from what I've seen it exceeds my expectations. Excellent work indeed!

**Comment by b-yp** [comment]
Thank you, I have only implemented the functionality temporarily, the style still needs to be optimized, and it needs to be compatible with light and dark themes.
