### ISSUE TITLE
Usage on MacOS

### ISSUE THREAD

**Issue by marcfree** [b-yp/logseq-insert-movie-properties#17]
Hi B-yp, thanks for creating this plugin. I've just installed it on MacOS 13.6.1, LogSeq 0.9.20, but can't call the menu on the page title. I guess, I've tried all combinations, but can not find the plug-ins menu :( I didn't find any setting for a menu shortcut. Can you tell me, what I'm missing :(
Thanks, Marc

**Comment by b-yp** [comment]
Hello, you need to enter the specific page; you can't find it in journals. After that, you'll be able to see the menu.
<img width="687" alt="image" src="https://github.com/b-yp/logseq-insert-movie-properties/assets/32813227/3bc02621-b578-409a-b0ab-64b6eb3419b6">

**Comment by marcfree** [comment]
👍 oh dear - the three dots....ok, sorry, haven't looked there - Thanks for your quick solution / guidance

**Comment by b-yp** [comment]
You're welcome. For the page name, you can right-click with the mouse or click on the three dots in the upper right corner to access the menu.
