### ISSUE TITLE
Show only English menu?

### ISSUE THREAD

**Issue by TigBuh99** [b-yp/logseq-insert-movie-properties#9]
This is a great plugin, but I cannot get it to show only the English menu items.

Also, could you make the menu options be shown together as a group in the dropdown menu?

**Comment by b-yp** [comment]
This is a great suggestion. Based on your suggestion, I plan to add an option in the settings to determine whether a specific command item should be displayed, allowing users to configure it themselves. As for the possibility of grouping menu items together, I will need to conduct further research on that. Thank you very much for your valuable suggestion. Thank you.

**Comment by TigBuh99** [comment]
Thank you for your response. Based on my brief experience with the plugin and maybe as advice to others, I notice that a great deal of pages are created for every movie etc. These include a page for each actor and others involved in the movie etc. I can foresee this can become too much over time. I think that the best solution, for me at least, is to have a graph explicitly for movies or TV series and therefore keep it separate from my main graph.

**Comment by b-yp** [comment]
Yes, your concerns are valid. You can create a separate graph to handle these tasks, avoiding contamination of the main graph. In the future, I plan to make each attribute a configurable item, allowing users to define the information they need and avoid introducing too much unnecessary information. Thank you once again for your valuable suggestion ❤️.

**Comment by b-yp** [comment]
I have released a new version that supports configuring the visibility of menu items. Regarding displaying menu items in the same group, I couldn't find a corresponding API, so I added an emoji prefix to each menu item and also made it possible to modify the prefix.

**Comment by TigBuh99** [comment]
Thanks for the update. The menus are fixed now and they are nicer, but the page properties are still in Chinese!

**Comment by b-yp** [comment]
Can you take a screenshot of this so I can take a look? I'm having a bit of trouble understanding.

**Comment by TigBuh99** [comment]
![CopyQ rUrfBy](https://github.com/b-yp/logseq-insert-movie-properties/assets/49759462/8495ddde-66d9-48c5-8472-5d7a2eaf9667)
The leftmost column shows the properties in Chinese!

**Comment by b-yp** [comment]
I find it strange because I have already removed the Chinese attribute feature. In theory, all the 'insert' now should have English attributes. I just tested it, and it seems to be working that way. You can try uninstalling the plugin and then reinstalling it. If the issue persists, I can release another version that completely removes the Chinese attribute.

**Comment by TigBuh99** [comment]
I uninstalled the plugin, closed and reopened Logseq, installed the plugin again, changed the settings to the English menu, closed and reopened Logseq. Unfortunately, it still shows the attributes in Chinese.

**Comment by TigBuh99** [comment]
This character is also in Chinese in the page properties: 分钟 I assume it means "minutes".

**Comment by b-yp** [comment]
Since that's the case, I will release a version that completely removes the Chinese attribute. This process may take about half an hour.

**Comment by b-yp** [comment]
A new version has been released, removing Chinese attributes and standardizing attribute writing.

**Comment by TigBuh99** [comment]
It works perfectly as far as the page properties are concerned. I have another issue with the TV series that if you don't mind I should mention separately.

**Comment by b-yp** [comment]
Okay, please create a separate issue for that.
